version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"